# Complete Whis Observability Stack
version: '3.8'

services:
  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: whis-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    networks:
      - whis-network
    restart: unless-stopped

  # Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: whis-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=whis123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - whis-network
    restart: unless-stopped
    depends_on:
      - prometheus

  # Splunk for SIEM (using free version)
  splunk:
    image: splunk/splunk:latest
    container_name: whis-splunk
    ports:
      - "8000:8000"   # Web UI
      - "8088:8088"   # HEC
      - "9997:9997"   # Indexer
    volumes:
      - splunk_data:/opt/splunk/var
      - ./monitoring/splunk/default.yml:/tmp/defaults/default.yml
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=whis123456
      - SPLUNK_HEC_TOKEN=whis-hec-token-2025
    networks:
      - whis-network
    restart: unless-stopped

  # ElasticSearch for log aggregation
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: whis-elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - whis-network
    restart: unless-stopped

  # Kibana for log visualization
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: whis-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - whis-network
    restart: unless-stopped
    depends_on:
      - elasticsearch

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: whis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - whis-network
    restart: unless-stopped

  # PostgreSQL for persistent data
  postgres:
    image: postgres:15
    container_name: whis-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=whis_soar
      - POSTGRES_USER=whis
      - POSTGRES_PASSWORD=whis123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./monitoring/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - whis-network
    restart: unless-stopped

  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: whis-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - whis-network
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
  splunk_data:
  elasticsearch_data:
  redis_data:
  postgres_data:

networks:
  whis-network:
    driver: bridge