apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "whis-*"
    basicAuth: false
    
  - name: Splunk
    type: splunk
    access: proxy
    url: http://splunk:8089
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: whis123456