# Data Governance Configuration (PII Protection, Dataset Versioning)
# CRITICAL for GDPR/HIPAA compliance

pii_patterns:
  # Email addresses
  email: '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
  
  # Social Security Numbers
  ssn: '\b\d{3}-?\d{2}-?\d{4}\b'
  
  # Credit card numbers
  credit_card: '\b\d{4}[-\s]?\d{4}[-\s]?\d{4}[-\s]?\d{4}\b'
  
  # Phone numbers
  phone: '\b\d{3}[-.]?\d{3}[-.]?\d{4}\b'
  
  # IP addresses (may contain PII in logs)
  ip_address: '\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b'
  
  # API keys and tokens
  api_key: '\b[A-Za-z0-9]{32,}\b'
  password_field: '(?i)(password|pwd|pass)\s*[:=]\s*[^\s]+'
  token: '(?i)(token|jwt|bearer)\s*[:=]\s*[A-Za-z0-9._-]+'
  secret: '(?i)(secret|key)\s*[:=]\s*[A-Za-z0-9._-]+'
  
  # User identifiers
  username: '(?i)(username|user|login)\s*[:=]\s*[A-Za-z0-9._-]+'
  
  # Cloud provider keys
  aws_key: '\bAKIA[0-9A-Z]{16}\b'
  gcp_key: '\b[A-Za-z0-9_]{40}\b'
  azure_key: '\b[A-Za-z0-9/+=]{44}\b'
  
  # Private keys
  private_key: '-----BEGIN (RSA |EC |DSA )?PRIVATE KEY-----'
  
  # Database connection strings
  db_connection: '(?i)(jdbc|mongodb|postgres|mysql)://[^\s]+'
  
  # File paths that might contain usernames
  file_path: '[C-Z]:\\\\Users\\\\[^\\\\]+\\\\'

redaction_policy:
  method: "hash"              # hash, mask, or remove
  preserve_format: true       # Maintain original length/structure
  audit_enabled: true         # Log all redactions for compliance
  
security:
  strict_mode: true           # Fail on unknown patterns
  unknown_pattern_action: "flag"  # flag, redact, or ignore
  min_redaction_length: 4     # Minimum length to trigger redaction
  
dataset_versioning:
  version_control: true       # Track dataset versions
  hash_algorithm: "sha256"    # For dataset integrity
  metadata_required:          # Required metadata fields
    - "source"
    - "collection_date"
    - "sanitization_date"
    - "approval_status"
    
compliance:
  gdpr:
    enabled: true
    retention_days: 365       # Data retention period
    consent_required: true
    
  hipaa:
    enabled: false            # Enable for healthcare data
    phi_detection: true       # Protected Health Information detection
    
  pci:
    enabled: true             # Payment card data protection
    mask_pan: true            # Mask Primary Account Numbers
    
audit_settings:
  log_level: "INFO"
  output_format: "json"
  retention_days: 2555        # 7 years for compliance
  encryption_enabled: true    # Encrypt audit logs
  
quality_gates:
  max_pii_detections: 0       # Fail if PII detected after redaction
  min_examples_required: 10   # Minimum examples for valid dataset
  max_duplicate_ratio: 0.1    # Maximum allowed duplicate examples